# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c45efa14ff72119007b47e29116cd802e80fef5c4b014353d13d09300e2ad0e8971edec3327f3413dda32c9994e1c985796f25422a9ad18a70ace55d55022f6

test:
  secret_key_base: dad9ad1019a731adfcae5d5d88a535648457ebde02a5d3de4ed38dc17cca5e572dc1f33a4b8b2d73d5c2fdd774e40564845a70d8c401ca48264b58627a8f52d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
